allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: false
  unrs-resolver: false

packages:
  - "apps/*"
  - "packages/*"

patchedDependencies:
  '@better-auth/infra@0.3.6': patches/@better-auth__infra@0.3.6.patch
